(use-modules (guile-tap))
(planned-tests 8)
(ok (eqv? 1 1) "A passing test")
(ok (not (null? '())) "A failing test")
(diagnostic "Skip some tests...")
(skip (eqv? 1 1))
(skip (not (eqv? 1 2)) "A description")
(diagnostic "Todo is supported as well...")
(todo (eqv? 1 2) "A note")
(todo (eqv? 1 1) "That is expected to fail, too")
(ok (throws? (/ 1 0)) "Test for exception")
(fail)
(ok #t "Another planned test")
