(use-modules (guile-tap))
(planned-tests 8)
(ok (eqv? 1 1) "A passing test")
(ok (not (null? '())) "A failing test")
(skip (eqv? 1 1) "A test which would pass")
(skip (not (eqv? 1 2)) "A test which would fail")
(todo (eqv? 1 2) "A failing test to be resolved")
(todo (eqv? 1 1) "A test which passes unexpectedly")
(ok (throws? (/ 1 0)) "Test for exception")
(exit)
(ok #t "Another planned test")
