(use-modules (guile-tap))
(diagnostics "Failing test suite for demonstration purposes")
(ok (eqv? 1 1) "A passing test")
(ok (not (null? '())) "A failing test")
(ok (eqv? 1 (call-with-input-file "nosuchfile.txt" (lambda (port) 1))) "Erroneous test")
(skip (eqv? 1 1) "Skip a test which would pass")
(skip (not (eqv? 1 2)) "Skip a test which would fail")
(todo (eqv? 1 2) "A failing test to be resolved")
(todo (eqv? 1 1) "A test which passes unexpectedly")
(ok (throws? (/ 1 0)) "Test for exception")
(ok #t "Another planned test")
(run-tests)
(format #t "ok 10 - An unplanned test~&")
